kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
  namespace: better-bags
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
reclaimPolicy: Retain
volumeBindingMode: Immediate